import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const copyStaticPlugin = {
	name: "copy-static",
	setup(build) {
		build.onStart(async () => {
			await fs.mkdir("dist", { recursive: true });
		});
		build.onEnd(async () => {
			try {
				await fs.copyFile("src/styles.css", "dist/styles.css");
			} catch (_) {
				// styles.css is optional
			}
			try {
				await fs.copyFile("src/manifest.json", "dist/manifest.json");
			} catch (_) {
				// manifest.json should exist during packaging, ignore in dev if absent
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
	platform: "node",
	plugins: [copyStaticPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
